XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX


BBBBB BBBBBBB

BB BBBBBBBBBBB
XXXXXXX XXXXXXXX XXX XXXXXXXX XXXXXX XXXXXX XXXXXX XXX XXXXXXXXXX
BBBBB

BB BBBB
    BB BBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX XX XXXX XXXXX XX XXXXXXXX
    XXXXXX XXXXX XXXX XX XXXXXXX XXXX XXX XXXXXXXXXXX
    BBBB
    XXXXXXXXX XXXXX XX XXX XXXX XXXXXXXXX
    BBBBB
BBBBB

XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBBBB
XXXXXXX
XXXX
    XXXXXXXXX
    XXXXXXXXX
XXXXX
XXXX
    XXXXXXXXX
    XXXXXXXXX
XXXXX
XXXXXXXX

XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX
XXXXXXX


XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXXXX

BBBBBBBB
XXXXXXX
XXXXXXX