# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'article title', max_length=50, verbose_name=b'title')),
                ('content', models.TextField(help_text=b'content', verbose_name=b'content')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name=b'create time')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name=b'update time')),
                ('tags', models.CharField(help_text=b'tags', max_length=30, null=True, verbose_name=b'tags')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, unique=True, verbose_name=b'author name')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (0, 'female')], help_text=b'sex', verbose_name=b'sex')),
                ('age', models.IntegerField(default=0, help_text=b'age', null=True, verbose_name=b'age')),
                ('status', models.BooleanField(default=True, help_text=b'user status', verbose_name=b'status')),
            ],
        ),
    ]
