# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='wswang', help_text='\u6587\u7ae0\u4f5c\u8005', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.CharField(default='wswang', help_text='\u6587\u7ae0\u5206\u7c7b', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='\u6587\u7ae0\u9898\u76ee', max_length=50, verbose_name=b'title'),
        ),
    ]
