# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160521_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='classify',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='\u8bd7\u60c5\u753b\u610f', help_text='\u6587\u7ae0\u5206\u7c7b', max_length=255),
        ),
    ]
