# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160521_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(0, '\u884c\u4e91\u6d41\u6c34'), (1, '\u7a0b\u5e8f\u4eba\u751f'), (2, '\u75f4\u4eba\u8bf4\u68a6')], default=1, help_text='\u6587\u7ae0\u5206\u7c7b'),
        ),
    ]
