# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160523_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='\u9884\u77e5\u8be6\u60c5\uff0c\u8bf7\u7ee7\u7eed\u9605\u8bfb', help_text='\u6587\u7ae0\u6458\u8981', max_length=255),
            preserve_default=False,
        ),
    ]
