# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u7c7b\u522b\u540d\u79f0', max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name=b'create time')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name=b'update time')),
            ],
            options={
                'verbose_name': 'category',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='\u5206\u7c7b', on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
