# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.TimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'message board',
            },
        ),
    ]
