# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='message',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
