# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('todo', models.TextField()),
            ],
            options={
                'verbose_name': 'todolist',
            },
        ),
    ]
